#!/bin/sh

if ! which sass > /dev/null; then npm i --global sass; fi;
rm -rf deploy;
mkdir -p deploy/theme;
sass src/main.scss > deploy/theme/sane-discord.css;
cd src;
find . -type d -exec mkdir -p ../deploy/theme/{} \; ;
find . -name '*.svg' -exec cp {} ../deploy/theme/{} \; ;
cd ..;

